### ISSUE TITLE
Dist檔案無法Import

### ISSUE THREAD

**Issue by falconshark** [cunzaizhuyi/vue-draggable-progressbar#1]
用Vue cli預設的Template輸出的檔案是無法被直接匯入的，必須要調整Webpack的設定和改寫Index檔案才行。
我本來想幫你改寫，但發現Webpack 3的設定實在不會調...對不起。
給這個模板你參考看看：
https://github.com/prograhammer/vue-library-template

**Comment by cunzaizhuyi** [comment]
谢谢

**Comment by falconshark** [comment]
開了關於這個問題的Pull Requests：#2
